spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: RISK-ORGANOGRAMA
          uri: lb://RISK-ORGANOGRAMA
          predicates:
            - Path=/organograma/**
server:
  port: 9191
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

